/*
Copyright 2026 gzeuner - tiny-tool.de

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*/

/**
 * Test Scenario Generator
 * Creates test templates based on canonical analysis model
 * Supports Jest, TAP, and BDD-style test descriptions
 */

function generateTestScenarioName(program, changeContext = {}) {
  const { table, column, changeType } = changeContext;
  const base = `${program}`;
  if (table && column) return `${base} - ${changeType || 'Change'} to ${table}.${column}`;
  return base;
}

function generateJestTestTemplate(program, canonicalAnalysis, testContext = {}) {
  const { sqlStatements, tables, programCalls } = canonicalAnalysis.entities || {};
  const writeOps = sqlStatements ? sqlStatements.filter((s) => s.intent === 'WRITE') : [];
  const readOps = sqlStatements ? sqlStatements.filter((s) => s.intent === 'READ') : [];

  let test = `/**\n`;
  test += ` * ${program} - Test Suite\n`;
  test += ` * Auto-generated by Zeus PromptKit\n`;
  test += ` */\n\n`;
  test += `const { ${program.toLowerCase()} } = require('../src/${program.toLowerCase()}');\n`;
  test += `const DB = require('./fixtures/db.mock');\n\n`;

  test += `describe('${program}', () => {\n`;
  test += `  beforeEach(() => {\n`;
  test += `    DB.reset();\n`;
  test += `  });\n\n`;

  // Generate READ scenarios
  if (readOps.length > 0) {
    test += `  describe('READ operations', () => {\n`;
    readOps.forEach((op, idx) => {
      const tables = op.tables ? op.tables.join(', ') : 'tables';
      test += `    test('should read from ${tables}', async () => {\n`;
      test += `      const result = await ${program.toLowerCase()}.read();\n`;
      test += `      expect(result).toBeDefined();\n`;
      test += `    });\n\n`;
    });
    test += `  });\n\n`;
  }

  // Generate WRITE scenarios
  if (writeOps.length > 0) {
    test += `  describe('WRITE operations', () => {\n`;
    writeOps.forEach((op, idx) => {
      const tables = op.tables ? op.tables.join(', ') : 'tables';
      test += `    test('should write to ${tables}', async () => {\n`;
      test += `      const result = await ${program.toLowerCase()}.write({ /* data */ });\n`;
      test += `      expect(result.success).toBe(true);\n`;
      test += `    });\n\n`;

      test += `    test('should handle errors when writing to ${tables}', async () => {\n`;
      test += `      DB.simulateError('${tables.split(',')[0]}');\n`;
      test += `      const result = await ${program.toLowerCase()}.write({ /* data */ });\n`;
      test += `      expect(result.success).toBe(false);\n`;
      test += `      expect(result.error).toBeDefined();\n`;
      test += `    });\n\n`;
    });
    test += `  });\n`;
  }

  test += `});\n`;
  return test;
}

function generateMarkdownTestPlan(program, canonicalAnalysis, options = {}) {
  const { sqlStatements, tables, relations } = canonicalAnalysis.entities || {};
  const writeOps = sqlStatements ? sqlStatements.filter((s) => s.intent === 'WRITE') : [];
  const readOps = sqlStatements ? sqlStatements.filter((s) => s.intent === 'READ') : [];
  const { isCriticalPath } = options;

  let markdown = `# Test Plan: ${program}\n\n`;
  markdown += `**Auto-generated by Zeus PromptKit** — for testing changes to ${program}\n\n`;

  // Test Scope
  markdown += `## Test Scope\n\n`;
  markdown += `| Category | Count |\n`;
  markdown += `|----------|-------|\n`;
  markdown += `| READ operations | ${readOps.length} |\n`;
  markdown += `| WRITE operations | ${writeOps.length} |\n`;
  markdown += `| Related programs | ${canonicalAnalysis.entities.programCalls ? canonicalAnalysis.entities.programCalls.length : 0} |\n\n`;

  // Unit Tests
  markdown += `## Unit Tests (Jest)\n\n`;
  markdown += `### 1. Basic Functionality\n`;
  markdown += `- [ ] ${program} initializes without errors\n`;
  markdown += `- [ ] ${program} loads all required modules\n`;
  markdown += `- [ ] ${program} executes without SQL errors\n\n`;

  // READ Tests
  if (readOps.length > 0) {
    markdown += `### 2. READ Operations (${readOps.length})\n`;
    readOps.forEach((op) => {
      const tables = op.tables ? op.tables.join(', ') : '?';
      markdown += `- [ ] SELECT from ${tables} returns correct structure\n`;
      markdown += `- [ ] SELECT handles NULL values correctly\n`;
      markdown += `- [ ] SELECT handles empty result sets\n`;
    });
    markdown += '\n';
  }

  // WRITE Tests
  if (writeOps.length > 0) {
    markdown += `### 3. WRITE Operations (${writeOps.length})\n`;
    writeOps.forEach((op) => {
      const tables = op.tables ? op.tables.join(', ') : '?';
      const opType = op.type || 'UPDATE';
      markdown += `- [ ] ${opType} to ${tables} succeeds with valid data\n`;
      markdown += `- [ ] ${opType} to ${tables} rejects invalid data\n`;
      markdown += `- [ ] ${opType} rolls back on error\n`;
    });
    markdown += '\n';
  }

  // Integration Tests
  markdown += `## Integration Tests (Business Flow)\n\n`;
  markdown += `### Happy Path Scenario\n`;
  markdown += `\`\`\`\n`;
  markdown += `1. Initialize ${program} with valid config\n`;
  markdown += `2. Load data from source tables\n`;
  markdown += `3. Process and transform\n`;
  markdown += `4. Write results to target tables\n`;
  markdown += `5. Verify audit trail\n`;
  markdown += `\`\`\`\n\n`;

  markdown += `### Error Scenarios\n`;
  markdown += `- [ ] Handle DB connection timeout\n`;
  markdown += `- [ ] Handle constraint violations\n`;
  markdown += `- [ ] Handle missing permissions\n`;
  markdown += `- [ ] Handle transaction rollback\n\n`;

  if (isCriticalPath) {
    markdown += `## ⚠️  Critical Path Testing\n\n`;
    markdown += `**This program is involved in critical workflow transitions. Extended testing required:**\n\n`;
    markdown += `- [ ] State transitions tested exhaustively\n`;
    markdown += `- [ ] Rollback scenarios covered\n`;
    markdown += `- [ ] Error messages logged\n`;
    markdown += `- [ ] Recovery procedures documented\n\n`;
  }

  markdown += `## Regression Tests\n\n`;
  markdown += `- [ ] Old data patterns still work\n`;
  markdown += `- [ ] Performance unchanged (within 10%)\n`;
  markdown += `- [ ] No new warnings logged\n\n`;

  return markdown;
}

/**
 * Generate comprehensive test scenario for a specific change
 */
function generateChangeTestScenario(program, changeContext = {}) {
  const { table, column, oldType, newType, affectedPrograms } = changeContext;

  let scenario = `# Test Scenario: ${program}\n\n`;
  scenario += `**Change:** Add/Modify column \`${column}\` in table \`${table}\`\n`;
  scenario += `**Old Type:** ${oldType || 'N/A'}\n`;
  scenario += `**New Type:** ${newType || 'N/A'}\n\n`;

  if (affectedPrograms && affectedPrograms.length > 0) {
    scenario += `## Affected Programs (${affectedPrograms.length})\n\n`;
    affectedPrograms.forEach((prog) => {
      scenario += `- ${prog.name}: ${prog.accessType} (${prog.accessCount} access points)\n`;
    });
    scenario += '\n';
  }

  scenario += `## Pre-Implementation Test Checklist\n\n`;
  scenario += `- [ ] DDL change compiled successfully\n`;
  scenario += `- [ ] Column exists with correct type\n`;
  scenario += `- [ ] DEFAULT value set correctly\n`;
  scenario += `- [ ] NOT NULL constraints respected\n\n`;

  scenario += `## Post-Implementation Test Checklist\n\n`;
  scenario += `- [ ] All affected programs recompiled\n`;
  scenario += `- [ ] SELECT queries still return correct results\n`;
  scenario += `- [ ] INSERT/UPDATE operations work\n`;
  scenario += `- [ ] New column can be read and written\n`;
  scenario += `- [ ] NULL handling correct\n`;
  scenario += `- [ ] Type conversions work (if needed)\n\n`;

  scenario += `## Data Validation Tests\n\n`;
  scenario += `### Valid Data\n`;
  scenario += `\`\`\`sql\n`;
  scenario += `SELECT * FROM ${table} WHERE ${column} IS NOT NULL;\n`;
  scenario += `\`\`\`\n\n`;

  scenario += `### Edge Cases\n`;
  scenario += `- NULL values\n`;
  scenario += `- MIN/MAX values\n`;
  scenario += `- Special characters\n`;
  scenario += `- Type boundary values\n\n`;

  return scenario;
}

module.exports = {
  generateJestTestTemplate,
  generateMarkdownTestPlan,
  generateChangeTestScenario,
  generateTestScenarioName,
};
