graph TD
TABLE_001["TABLE_001 (TABLE)"]
PROGRAM_003["PROGRAM_003 (TABLE)"]
TABLE_002["TABLE_002 (TABLE)"]
PROGRAM_001["PROGRAM_001 (PROGRAM)"]
PROGRAM_004["PROGRAM_004 (PROGRAM)"]
PROGRAM_005["PROGRAM_005 (PROGRAM)"]
TABLE_003["TABLE_003 (TABLE)"]

PROGRAM_001 -->|USES_TABLE| PROGRAM_003
PROGRAM_001 -->|CALLS_PROGRAM| PROGRAM_004
PROGRAM_001 -->|CALLS_PROGRAM| PROGRAM_005
PROGRAM_004 -->|USES_TABLE| TABLE_001
PROGRAM_004 -->|USES_TABLE| TABLE_003
PROGRAM_005 -->|USES_TABLE| TABLE_002
