/*
Copyright 2026 gzeuner - tiny-tool.de

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
*/

const CONFIG_UI_METADATA_VERSION = '1.0.0';

const CONFIG_UI_SECTIONS = Object.freeze([
  Object.freeze({ id: 'profile', label: 'Profile Selection', order: 10 }),
  Object.freeze({ id: 'workspace', label: 'Workspace Paths', order: 20 }),
  Object.freeze({ id: 'db2', label: 'DB2 Connections', order: 30 }),
  Object.freeze({ id: 'fetch', label: 'Source Fetch', order: 40 }),
  Object.freeze({ id: 'analysis', label: 'Analysis Defaults', order: 50 }),
  Object.freeze({ id: 'workflow', label: 'Workflow Presets', order: 60 }),
  Object.freeze({ id: 'cli', label: 'Command-Time Options', order: 70 }),
]);

const CONFIG_UI_FIELDS = Object.freeze([
  Object.freeze({
    key: 'runtime.profile',
    label: 'Profile Name',
    description: 'Selected profile for command execution.',
    section: 'profile',
    type: 'string',
    required: true,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'dev',
    example: 'dev',
    envVar: null,
    profilePath: null,
    validation: Object.freeze({ pattern: '^[a-zA-Z0-9._-]+$' }),
    sources: Object.freeze(['cli']),
    capabilities: Object.freeze(['fetch', 'analyze', 'query', 'doctor', 'workflow']),
  }),
  Object.freeze({
    key: 'runtime.configPath',
    label: 'Config Directory',
    description: 'Directory or JSON file path that contains profiles configuration.',
    section: 'profile',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './config',
    example: './config',
    envVar: 'ZEUS_CONFIG_DIR',
    profilePath: null,
    validation: Object.freeze({ acceptsJsonFile: true }),
    sources: Object.freeze(['cli', 'env']),
    capabilities: Object.freeze(['global']),
  }),
  Object.freeze({
    key: 'profile.sourceRoot',
    label: 'Local Source Root',
    description: 'Directory containing RPG/CL/DDS source for analysis.',
    section: 'workspace',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './workspace/source',
    example: './workspace/source',
    envVar: 'ZEUS_SOURCE_ROOT',
    profilePath: 'sourceRoot',
    validation: Object.freeze({ mustExistForAnalyze: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['analyze', 'workflow']),
  }),
  Object.freeze({
    key: 'profile.outputRoot',
    label: 'Output Root',
    description: 'Directory used for generated analysis artifacts.',
    section: 'workspace',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './workspace/output',
    example: './workspace/output',
    envVar: 'ZEUS_OUTPUT_ROOT',
    profilePath: 'outputRoot',
    validation: Object.freeze({ writablePath: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['analyze', 'workflow', 'serve']),
  }),
  Object.freeze({
    key: 'profile.analysesRegistryPath',
    label: 'Analyses Registry Path',
    description: 'Optional path to analyses registry JSON file.',
    section: 'workspace',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './analysis/_registry.json',
    example: './analysis/_registry.json',
    envVar: 'ZEUS_ANALYSES_REGISTRY',
    profilePath: 'analysesRegistryPath',
    validation: Object.freeze({ fileExtension: '.json' }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['serve', 'analyses']),
  }),
  Object.freeze({
    key: 'profile.db.host',
    label: 'DB2 Host',
    description: 'IBM i host for default DB2 connection.',
    section: 'db2',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'example.ibm.local',
    example: 'example.ibm.local',
    envVar: 'ZEUS_DB_HOST',
    profilePath: 'db.host',
    validation: Object.freeze({ mutuallyExclusiveWith: 'profile.db.url' }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['query', 'analyze', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.db.url',
    label: 'DB2 JDBC URL',
    description: 'Optional JDBC URL for DB2 connectivity.',
    section: 'db2',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'jdbc:as400://example.ibm.local;naming=system',
    example: 'jdbc:as400://example.ibm.local;naming=system',
    envVar: 'ZEUS_DB_URL',
    profilePath: 'db.url',
    validation: Object.freeze({ startsWith: 'jdbc:' }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['query', 'analyze', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.db.user',
    label: 'DB2 User',
    description: 'DB2 login user for metadata/query access.',
    section: 'db2',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'YOUR_IBM_I_USER',
    example: 'YOUR_IBM_I_USER',
    envVar: 'ZEUS_DB_USER',
    profilePath: 'db.user',
    validation: Object.freeze({ minLength: 1 }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['query', 'analyze', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.db.password',
    label: 'DB2 Password',
    description: 'DB2 login password. Should usually come from environment variables.',
    section: 'db2',
    type: 'password',
    required: false,
    sensitive: true,
    safeToDisplay: false,
    placeholder: '${env:ZEUS_DB_PASSWORD}',
    example: '${env:ZEUS_DB_PASSWORD}',
    envVar: 'ZEUS_DB_PASSWORD',
    profilePath: 'db.password',
    validation: Object.freeze({ allowEnvPlaceholder: true }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['query', 'analyze', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.db.defaultSchema',
    label: 'DB2 Default Schema',
    description: 'Default schema/library for read-only queries.',
    section: 'db2',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'DATA_EXAMPLE',
    example: 'DATA_EXAMPLE',
    envVar: 'ZEUS_DB_DEFAULT_SCHEMA',
    profilePath: 'db.defaultSchema',
    validation: Object.freeze({ uppercaseRecommended: true }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['query', 'analyze']),
  }),
  Object.freeze({
    key: 'profile.dbRoles.metadata',
    label: 'Metadata DB Role',
    description: 'Optional role-specific DB2 override for metadata lookups.',
    section: 'db2',
    type: 'object',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '{ "system": "readonly" }',
    example: '{ "system": "readonly" }',
    envVar: null,
    profilePath: 'dbRoles.metadata',
    validation: Object.freeze({ allowedKeys: ['host', 'url', 'user', 'password', 'defaultSchema', 'defaultLibrary', 'system'] }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['analyze', 'query', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.dbRoles.testData',
    label: 'Test Data DB Role',
    description: 'Optional role-specific DB2 override for test-data reads.',
    section: 'db2',
    type: 'object',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '{ "system": "dev" }',
    example: '{ "system": "dev" }',
    envVar: null,
    profilePath: 'dbRoles.testData',
    validation: Object.freeze({ allowedKeys: ['host', 'url', 'user', 'password', 'defaultSchema', 'defaultLibrary', 'system'] }),
    sources: Object.freeze(['profile', 'env']),
    capabilities: Object.freeze(['analyze', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.fetch.host',
    label: 'Fetch Host',
    description: 'IBM i host used for source fetch.',
    section: 'fetch',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'example.ibm.local',
    example: 'example.ibm.local',
    envVar: 'ZEUS_FETCH_HOST',
    profilePath: 'fetch.host',
    validation: Object.freeze({ minLength: 1 }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.fetch.user',
    label: 'Fetch User',
    description: 'IBM i user for source fetch.',
    section: 'fetch',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'YOUR_IBM_I_USER',
    example: 'YOUR_IBM_I_USER',
    envVar: 'ZEUS_FETCH_USER',
    profilePath: 'fetch.user',
    validation: Object.freeze({ minLength: 1 }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.fetch.password',
    label: 'Fetch Password',
    description: 'IBM i password for source fetch.',
    section: 'fetch',
    type: 'password',
    required: false,
    sensitive: true,
    safeToDisplay: false,
    placeholder: '${env:ZEUS_FETCH_PASSWORD}',
    example: '${env:ZEUS_FETCH_PASSWORD}',
    envVar: 'ZEUS_FETCH_PASSWORD',
    profilePath: 'fetch.password',
    validation: Object.freeze({ allowEnvPlaceholder: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch', 'doctor']),
  }),
  Object.freeze({
    key: 'profile.fetch.sourceLibrary',
    label: 'Source Library',
    description: 'IBM i source library used by fetch.',
    section: 'fetch',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'SOURCE_EXAMPLE',
    example: 'SOURCE_EXAMPLE',
    envVar: 'ZEUS_FETCH_SOURCE_LIBRARY',
    profilePath: 'fetch.sourceLibrary',
    validation: Object.freeze({ uppercaseRecommended: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.sourceFiles',
    label: 'Source Files',
    description: 'Comma-separated source files to fetch from the source library.',
    section: 'fetch',
    type: 'stringArray',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'QRPGLESRC,QCPYSRC,QCLLESRC',
    example: '["QRPGLESRC", "QCPYSRC"]',
    envVar: 'ZEUS_FETCH_SOURCE_FILES',
    profilePath: 'fetch.sourceFiles',
    validation: Object.freeze({ itemPattern: '^[A-Z0-9_#$@]+$' }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.members',
    label: 'Members Filter',
    description: 'Optional list of source members to fetch.',
    section: 'fetch',
    type: 'stringArray',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'ORDERPGM,CUSTSRV',
    example: '["ORDERPGM", "CUSTSRV"]',
    envVar: 'ZEUS_FETCH_MEMBERS',
    profilePath: 'fetch.members',
    validation: Object.freeze({ itemPattern: '^[A-Z0-9_#$@]+$' }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.ifsDir',
    label: 'Remote IFS Export Directory',
    description: 'IFS directory on IBM i used as fetch export source.',
    section: 'fetch',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '/ifs/source-export/example',
    example: '/ifs/source-export/example',
    envVar: 'ZEUS_FETCH_IFS_DIR',
    profilePath: 'fetch.ifsDir',
    validation: Object.freeze({ mustStartWithSlash: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.out',
    label: 'Local Fetch Output',
    description: 'Local output directory where fetched sources are stored.',
    section: 'fetch',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './fetched-source/dev',
    example: './fetched-source/dev',
    envVar: 'ZEUS_FETCH_OUT',
    profilePath: 'fetch.out',
    validation: Object.freeze({ writablePath: true }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.transport',
    label: 'Fetch Transport',
    description: 'Preferred protocol for fetch.',
    section: 'fetch',
    type: 'enum',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'auto',
    example: 'auto',
    envVar: 'ZEUS_FETCH_TRANSPORT',
    profilePath: 'fetch.transport',
    validation: Object.freeze({ allowedValues: ['auto', 'sftp', 'jt400', 'ftp'] }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.preferTransport',
    label: 'Preferred Transport Hint',
    description: 'Hint for auto mode to pick sftp, jt400, or ftp first.',
    section: 'fetch',
    type: 'enum',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'sftp',
    example: 'sftp',
    envVar: 'ZEUS_FETCH_PREFER_TRANSPORT',
    profilePath: 'fetch.preferTransport',
    validation: Object.freeze({ allowedValues: ['sftp', 'jt400', 'ftp', 'auto'] }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.transportTimeoutMs',
    label: 'Transport Timeout (ms)',
    description: 'Timeout for transport-level fetch operations.',
    section: 'fetch',
    type: 'number',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '30000',
    example: '30000',
    envVar: 'ZEUS_FETCH_TRANSPORT_TIMEOUT_MS',
    profilePath: 'fetch.transportTimeoutMs',
    validation: Object.freeze({ min: 1000 }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.streamFileCcsid',
    label: 'Stream File CCSID',
    description: 'Target CCSID used for fetched stream files.',
    section: 'fetch',
    type: 'number',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '1208',
    example: '1208',
    envVar: 'ZEUS_FETCH_STREAMFILE_CCSID',
    profilePath: 'fetch.streamFileCcsid',
    validation: Object.freeze({ min: 1 }),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.fetch.replace',
    label: 'Replace Existing Local Files',
    description: 'If true, existing local fetched files are overwritten.',
    section: 'fetch',
    type: 'boolean',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'true',
    example: 'true',
    envVar: 'ZEUS_FETCH_REPLACE',
    profilePath: 'fetch.replace',
    validation: Object.freeze({}),
    sources: Object.freeze(['profile', 'env', 'cli']),
    capabilities: Object.freeze(['fetch']),
  }),
  Object.freeze({
    key: 'profile.extensions',
    label: 'Analyze Extensions',
    description: 'File extensions included in source scan and analysis.',
    section: 'analysis',
    type: 'stringArray',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '.rpgle,.sqlrpgle,.clle,.dds',
    example: '[".rpgle", ".sqlrpgle", ".clle"]',
    envVar: null,
    profilePath: 'extensions',
    validation: Object.freeze({ itemPattern: '^\\.[a-z0-9]+$' }),
    sources: Object.freeze(['profile', 'cli']),
    capabilities: Object.freeze(['analyze', 'workflow']),
  }),
  Object.freeze({
    key: 'profile.contextOptimizer.softTokenLimit',
    label: 'Context Token Limit',
    description: 'Soft token limit used by context optimizer.',
    section: 'analysis',
    type: 'number',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '10000',
    example: '10000',
    envVar: null,
    profilePath: 'contextOptimizer.softTokenLimit',
    validation: Object.freeze({ min: 1000 }),
    sources: Object.freeze(['profile']),
    capabilities: Object.freeze(['analyze']),
  }),
  Object.freeze({
    key: 'profile.analysisLimits.maxPrograms',
    label: 'Max Programs',
    description: 'Safety limit for total analyzed programs per run.',
    section: 'analysis',
    type: 'number',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '500',
    example: '500',
    envVar: null,
    profilePath: 'analysisLimits.maxPrograms',
    validation: Object.freeze({ min: 1 }),
    sources: Object.freeze(['profile']),
    capabilities: Object.freeze(['analyze']),
  }),
  Object.freeze({
    key: 'profile.testData.limit',
    label: 'Test Data Row Limit',
    description: 'Maximum rows returned by test-data extraction features.',
    section: 'analysis',
    type: 'number',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: '50',
    example: '50',
    envVar: null,
    profilePath: 'testData.limit',
    validation: Object.freeze({ min: 1 }),
    sources: Object.freeze(['profile', 'cli']),
    capabilities: Object.freeze(['analyze']),
  }),
  Object.freeze({
    key: 'profile.workflow.defaultPreset',
    label: 'Default Workflow Preset',
    description: 'Preset name used by workflow run when no explicit preset is provided.',
    section: 'workflow',
    type: 'string',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'dev-end-to-end',
    example: 'dev-end-to-end',
    envVar: null,
    profilePath: 'workflow.defaultPreset',
    validation: Object.freeze({ minLength: 1 }),
    sources: Object.freeze(['profile']),
    capabilities: Object.freeze(['workflow']),
  }),
  Object.freeze({
    key: 'profile.workflow.analyzeModes',
    label: 'Workflow Analyze Modes',
    description: 'Analyze modes used in profile workflow defaults and presets.',
    section: 'workflow',
    type: 'stringArray',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'documentation,defect-analysis',
    example: '["documentation", "defect-analysis"]',
    envVar: null,
    profilePath: 'workflow.analyzeModes',
    validation: Object.freeze({ minItems: 1 }),
    sources: Object.freeze(['profile']),
    capabilities: Object.freeze(['workflow']),
  }),
  Object.freeze({
    key: 'profile.workCopy.root',
    label: 'Work Copy Root',
    description: 'Workspace directory used by copy-to-workspace and diff flows.',
    section: 'workflow',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'workspace-source/',
    example: 'workspace-source/',
    envVar: null,
    profilePath: 'workCopy.root',
    validation: Object.freeze({ writablePath: true }),
    sources: Object.freeze(['profile']),
    capabilities: Object.freeze(['copy', 'diff']),
  }),
  Object.freeze({
    key: 'cli.source',
    label: 'Analyze Source Override',
    description: 'Command-time source path override for analyze/workflow commands.',
    section: 'cli',
    type: 'path',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: './rpg_sources',
    example: './rpg_sources',
    envVar: null,
    profilePath: null,
    validation: Object.freeze({ cliOnly: true }),
    sources: Object.freeze(['cli']),
    capabilities: Object.freeze(['analyze', 'workflow']),
  }),
  Object.freeze({
    key: 'cli.program',
    label: 'Program / Member Selector',
    description: 'Primary analyze target provided per command.',
    section: 'cli',
    type: 'string',
    required: true,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'ORDERPGM',
    example: 'ORDERPGM',
    envVar: null,
    profilePath: null,
    validation: Object.freeze({ cliOnly: true }),
    sources: Object.freeze(['cli']),
    capabilities: Object.freeze(['analyze', 'workflow', 'impact']),
  }),
  Object.freeze({
    key: 'cli.safeSharing',
    label: 'Safe Sharing',
    description: 'Command-time flag to redact sensitive output artifacts for sharing.',
    section: 'cli',
    type: 'boolean',
    required: false,
    sensitive: false,
    safeToDisplay: true,
    placeholder: 'false',
    example: 'true',
    envVar: null,
    profilePath: null,
    validation: Object.freeze({ cliOnly: true }),
    sources: Object.freeze(['cli']),
    capabilities: Object.freeze(['analyze', 'workflow', 'bundle']),
  }),
]);

function validateConfigUiMetadata(fields = CONFIG_UI_FIELDS, sections = CONFIG_UI_SECTIONS) {
  const errors = [];
  const sectionIds = new Set((sections || []).map((entry) => entry.id));
  const keys = new Set();
  const allowedTypes = new Set(['string', 'number', 'boolean', 'path', 'password', 'enum', 'stringArray', 'object']);

  for (const field of fields || []) {
    if (!field || typeof field !== 'object') {
      errors.push('each field must be an object');
      continue;
    }
    if (!field.key || typeof field.key !== 'string') {
      errors.push('field.key must be a non-empty string');
      continue;
    }
    if (keys.has(field.key)) {
      errors.push(`duplicate field key: ${field.key}`);
    }
    keys.add(field.key);
    if (!sectionIds.has(field.section)) {
      errors.push(`field "${field.key}" has unknown section "${field.section}"`);
    }
    if (!allowedTypes.has(field.type)) {
      errors.push(`field "${field.key}" has unsupported type "${field.type}"`);
    }
    if (typeof field.sensitive !== 'boolean') {
      errors.push(`field "${field.key}" must define boolean sensitive`);
    }
    if (typeof field.safeToDisplay !== 'boolean') {
      errors.push(`field "${field.key}" must define boolean safeToDisplay`);
    }
    if (field.sensitive === true && field.safeToDisplay !== false) {
      errors.push(`field "${field.key}" is sensitive and must set safeToDisplay=false`);
    }
    if (!Array.isArray(field.capabilities) || field.capabilities.length === 0) {
      errors.push(`field "${field.key}" must define at least one capability`);
    }
    if (!Array.isArray(field.sources) || field.sources.length === 0) {
      errors.push(`field "${field.key}" must define at least one source`);
    }
  }

  return errors;
}

function listConfigUiFields({ includeSensitive = true, section = null, capability = null } = {}) {
  return CONFIG_UI_FIELDS.filter((entry) => {
    if (!includeSensitive && entry.sensitive) return false;
    if (section && entry.section !== section) return false;
    if (capability && !entry.capabilities.includes(capability)) return false;
    return true;
  });
}

function getConfigUiField(key) {
  return CONFIG_UI_FIELDS.find((entry) => entry.key === key) || null;
}

const CONFIG_UI_METADATA_ERRORS = Object.freeze(validateConfigUiMetadata());
if (CONFIG_UI_METADATA_ERRORS.length > 0) {
  throw new Error(`Invalid config UI metadata: ${CONFIG_UI_METADATA_ERRORS.join('; ')}`);
}

module.exports = {
  CONFIG_UI_FIELDS,
  CONFIG_UI_METADATA_ERRORS,
  CONFIG_UI_METADATA_VERSION,
  CONFIG_UI_SECTIONS,
  getConfigUiField,
  listConfigUiFields,
  validateConfigUiMetadata,
};
