graph TD
ETCH["ETCH (TABLE)"]
FILE_100["FILE_100 (TABLE)"]
FILE_200["FILE_200 (TABLE)"]
MODULE_PROGRAM_100["PROGRAM_100 (MODULE)"]
MODULE_PROGRAM_200["PROGRAM_200 (MODULE)"]
MODULE_PROGRAM_300["PROGRAM_300 (MODULE)"]
PROGRAM_100["PROGRAM_100 (PROGRAM)"]
PROGRAM_200["PROGRAM_200 (PROGRAM)"]
PROGRAM_300["PROGRAM_300 (PROGRAM)"]
TABLE_100["TABLE_100 (TABLE)"]

PROGRAM_100 -->|USES_TABLE| ETCH
PROGRAM_100 -->|USES_TABLE| FILE_100
PROGRAM_100 -->|USES_TABLE| FILE_200
PROGRAM_100 -->|HAS_MODULE| MODULE_PROGRAM_100
PROGRAM_100 -->|HAS_MODULE| MODULE_PROGRAM_200
PROGRAM_100 -->|HAS_MODULE| MODULE_PROGRAM_300
PROGRAM_100 -->|CALLS_PROGRAM| PROGRAM_100
PROGRAM_100 -->|CALLS_PROGRAM| PROGRAM_200
PROGRAM_100 -->|CALLS_PROGRAM| PROGRAM_300
PROGRAM_100 -->|USES_TABLE| TABLE_100
