'use strict';

module.exports = {
  categories: {
    contract: [
      'tests/ai-knowledge-projection.test.js',
      'tests/analyze-run-manifest.test.js',
      'tests/bundle-manifest.test.js',
      'tests/cli-help.test.js',
      'tests/evidence-graph.test.js',
      'tests/graph-guided-context-planner.test.js',
      'tests/release-integrity.test.js',
      'tests/repository-control.test.js',
      'tests/fetch-readability-contract.test.js',
      'tests/schema-registry.test.js',
      'tests/task-oriented-analysis-index.test.js',
      'tests/tool-catalog-generator.test.js',
      'tests/tools-command.test.js',
      'tests/workflow-suggest.test.js',
      'tests/provider-contracts.test.js',
      'tests/provider-local-adapters.test.js',
      'tests/module-sdk.test.js',
      'tests/workflow-presets.test.js',
      'tests/community-deployment.test.js',
      'tests/project-intelligence-contracts.test.js',
      'tests/project-intelligence-store.test.js',
      'tests/project-intelligence-content.test.js',
      'tests/project-intelligence-search.test.js',
      'tests/project-intelligence-engine.test.js',
      'tests/project-intelligence-rpg-analyzer.test.js',
      'tests/project-intelligence-retrieval.test.js',
      'tests/project-intelligence-adapters.test.js',
      'tests/project-intelligence-hardening.test.js',
      'tests/knowledge-first.test.js',
      'tests/project-intelligence-export-corpora.test.js',
    ],
    smoke: [
      'tests/reproducible-output.test.js',
      'tests/safe-sharing.test.js',
      'tests/v1-smoke.test.js',
      'tests/provider-offline.test.js',
    ],
    corpus: ['tests/scanner-corpus.test.js'],
    e2e: [
      'tests/e2e/gui-workbench.e2e.test.js',
      'tests/e2e/mcp-stdio.e2e.test.js',
      'tests/e2e/sftp-fetch-analyze-bundle.e2e.test.js',
    ],
    benchmark: ['tests/analyze-benchmark.test.js', 'tests/project-intelligence-benchmark.test.js'],
    quality: [
      'tests/golden-quality.test.js',
      'tests/project-intelligence-retrieval-quality.test.js',
      'tests/project-intelligence-multi-program-recall.test.js',
    ],
    unit: [
      'tests/gui-workbench-contracts.test.js',
      'tests/local-ui-accessibility.test.js',
      'tests/plugin-workbench-contracts.test.js',
      'tests/profile-key-wizard-service.test.js',
      'tests/journal-row-diff.test.js',
      'tests/capability-registry.test.js',
      'tests/commercial-module-loader.test.js',
      'tests/knowledge-cli.test.js',
      'tests/knowledge-neutral-pui.test.js',
      'tests/knowledge-pipeline.test.js',
      'tests/test-inventory.test.js',
      'tests/typecheck-scope.test.js',
      'tests/consolidated-entitlement.test.js',
      'tests/consolidated-registration.test.js',
      'tests/consolidated-generationAssurance.test.js',
      'tests/consolidated-db2TestIntelligence.test.js',
      'tests/consolidated-ibmiValidation.test.js',
      'tests/consolidated-projectIntelligence.test.js',
      'tests/consolidated-productSurface.test.js',
      'tests/working-context.test.js',
    ],
  },
  exclusions: [],
};
